"use client";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "../components/ThemeProvider";
import { fontSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import NavBar from "@/components/layout/NavBar";
import { useSideBarOpen } from "@/hooks/useSideBarOpen";
import SideBar from "@/components/layout/SideBar";
import Head from "next/head";
import MarginWidthWrapper from "@/components/layout/MarginWidthWrapper";
import Header from "@/components/layout/Header";
import PageWrapper from "@/components/layout/PageWrapper";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { open, openSideBar } = useSideBarOpen();

  return (
    <html lang="en">
      <Head>
        {/* Any additional metadata you want to set */}
        <meta name="description" content="Custom description" />
      </Head>
      <body
        className={cn(
          " bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar openSideBar={openSideBar} />

          <main className="flex-1 flex-grow">
            {/* <MarginWidthWrapper> */}
            {/* <Header /> */}
            {/* <PageWrapper>{children}</PageWrapper> */}
            {/* </MarginWidthWrapper> */}
            {children}
          </main>

          <SideBar open={open} />
        </ThemeProvider>
      </body>
    </html>
  );
}
